---
title: "paper_miracidia_no_WSR"
author: "T Attenborough"
date: "2023-11-17"
output: html_document
---

```{r}
library(Seurat) #Seurat v4.0.2
library(dplyr)
library(patchwork)
library(here)
library(ggplot2)
library(clustree)
library(SingleCellExperiment)
library(scater)
library(DoubletFinder)
library(zellkonverter)
library(basilisk)
#sessionInfo()
```

```{r}
st=format(Sys.time(), "%Y-%m-%d") 
st
```


First, I will import the R objects containing the filtered sorted and unsorted cells
```{r}
run1.sample1.sorted.filt <- readRDS(file = "/Users/ta13/R_git/filtered_v10_miracidia/run1.v10.sample1.sorted.filt.rds")

run1.sample2.unsorted.filt <- readRDS(file = "/Users/ta13/R_git/filtered_v10_miracidia/run1.v10.sample2.unsorted.filt_52.rds")

run1.sample3.unsorted.filt <- readRDS(file = "/Users/ta13/R_git/filtered_v10_miracidia/run1.v10.sample3.unsorted.filt_52.rds")

run1.sample4.sorted.filt <- readRDS(file = "/Users/ta13/R_git/filtered_v10_miracidia/run1.v10.sample4.sorted.filt.rds")
```

```{r}
run1.sorted.filt <- merge(run1.sample1.sorted.filt, y = run1.sample4.sorted.filt, add.cell.ids = c("sample1", "sample4"), project = "mira_sorted")

run1.unsorted.filt <- merge(run1.sample2.unsorted.filt, y = run1.sample3.unsorted.filt, add.cell.ids = c("sample2", "sample3"), project = "mira_unsorted")
```

ID the W genes
```{r}
all_W <- read.csv("/Users/ta13/R_git/filtered_v10_miracidia/v10edit_WSR_gff_trim.csv", sep=c(','), header = FALSE)
all_W <- subset(all_W, V1 == 'gene' | V1 == 'pseudogenic_transcript')
just_W <- data.frame(do.call('rbind', strsplit(as.character(all_W$V2),';',fixed=TRUE)))
just_W <- data.frame(do.call('rbind', strsplit(as.character(just_W$X1),'=',fixed=TRUE)))

just_W$X2 <- gsub('\\_', '-', just_W$X2) #replace dashes with underscores

```

```{r}
run1.sorted.filt <- SCTransform(run1.sorted.filt, vars.to.regress = c("percent.mt", "plex"), verbose = FALSE, return.only.var.genes = FALSE)

run1.unsorted.filt <- SCTransform(run1.unsorted.filt, vars.to.regress = c("percent.mt", "plex"), verbose = FALSE, return.only.var.genes = FALSE)
```

Make a list of all the genes in the data, not including the gametologue genes
```{r}
mygenesS <- rownames(x = run1.sorted.filt)
head(mygenesS)
mygenesS <- data.frame(mygenesS)
colnames(mygenesS) <- "genes"
8645

mygenesU <- rownames(x = run1.unsorted.filt)
head(mygenesU)
mygenesU <- data.frame(mygenesU)
colnames(mygenesU) <- "genes"
8511

allmygenes <- rbind(mygenesS, mygenesU)
17156
allmygenes <- allmygenes %>%
  filter(duplicated(genes) == FALSE)
8747
mygenesNoW = subset(allmygenes, !(allmygenes$genes %in% just_W$X2))

8747-8718

write.csv(x = mygenesNoW, file = 'allmiragenes_noW.csv')
```

```{r}
run1.sorted.filt <- merge(run1.sample1.sorted.filt, y = run1.sample4.sorted.filt, add.cell.ids = c("sample1", "sample4"), project = "mira_sorted")

run1.unsorted.filt <- merge(run1.sample2.unsorted.filt, y = run1.sample3.unsorted.filt, add.cell.ids = c("sample2", "sample3"), project = "mira_unsorted")
```

```{r}
DefaultAssay(run1.sorted.filt) <- 'RNA'
no_W_sorted <- subset(run1.sorted.filt, features = mygenesNoW$genes)
DefaultAssay(run1.sorted.filt) <- 'SCT'
no_W_sorted <- subset(run1.sorted.filt, features = mygenesNoW$genes)
```

```{r}
DefaultAssay(run1.unsorted.filt) <- 'RNA'
no_W_unsorted <- subset(run1.unsorted.filt, features = mygenesNoW$genes)
DefaultAssay(run1.unsorted.filt) <- 'SCT'
no_W_unsorted <- subset(run1.unsorted.filt, features = mygenesNoW$genes)
```

```{r}
no_W_sorted <- SCTransform(no_W_sorted, vars.to.regress = c("percent.mt", "plex"), verbose = FALSE, return.only.var.genes = FALSE)

no_W_unsorted <- SCTransform(no_W_unsorted, vars.to.regress = c("percent.mt", "plex"), verbose = FALSE, return.only.var.genes = FALSE)
```

Find variable features
```{r}
type_list <- c(no_W_sorted, no_W_unsorted)
# select features that are repeatedly variable across datasets for integration
features <- SelectIntegrationFeatures(object.list = type_list, nfeatures = 3000)
type_list <- PrepSCTIntegration(object.list = type_list, anchor.features = features)
```

Identify anchors and integrate
```{r}
run1noZW.anchors <- FindIntegrationAnchors(object.list = type_list, anchor.features = features, normalization.method = "SCT")
# this command creates an 'integrated' data assay
run1.no_W <- IntegrateData(anchorset = run1noZW.anchors, normalization.method = "SCT")
```

```{r}
# specify that we will perform downstream analysis on the corrected data note that the
# original unmodified data still resides in the 'RNA' assay
DefaultAssay(run1.no_W) <- "integrated"

run1.no_W <- RunPCA(run1.no_W, npcs = 100, verbose = FALSE)
ElbowPlot(run1.no_W, ndims = 100)  #ranks PCs by percentage of variation. A clear dropoff is sometimes seen, though not really here.
ggsave("run1.nogameto.v10.integrated.elbow.pdf")

run1.no_W <- RunUMAP(run1.no_W, reduction = "pca", dims = 1:55)
run1.no_W <- FindNeighbors(run1.no_W, reduction = "pca", dims = 1:55)
run1.no_W <- FindClusters(run1.no_W, resolution = 0.5)

# Select a range of resolutions
resolution.range <- seq(from = 0, to = 1, by = 0.1)

# Find clusters using a range of resolutions
run1.no_W <- Seurat::FindClusters(object = run1.no_W, resolution = resolution.range)

clustree(run1.no_W)
ggsave("run1.no_W.clust_55PC_0_to_1_tree_SCT.pdf")
```

```{r}
run1.no_W <- RunUMAP(run1.no_W, reduction = "pca", dims = 1:55)
run1.no_W <- FindNeighbors(run1.no_W, reduction = "pca", dims = 1:55)
p2 <- DimPlot(run1.no_W, reduction = "umap", group.by = "plex", repel = TRUE, shuffle = TRUE)
p2
ggsave("run1.no_W-clust-55-PC_integrate_52_plex.pdf", width = 25, height = 15, units = c('cm'))

run1.no_W <- FindClusters(run1.no_W, resolution = 1)
p2 <- DimPlot(run1.no_W, reduction = "umap", label = TRUE, repel = TRUE)
p2
ggsave("run1.no_W-clust-55-PC-1-res_integrate_52_clean.pdf")
```

Import full dataset w labels
```{r}
run1.combined.v10 <- readRDS(file = "/Users/ta13/R_git/filtered_v10_miracidia/run1.combined.v10_integrated_55.rds")
```

```{r}
DefaultAssay(run1.combined.v10) <- "integrated"
run1.combined.v10 <- RenameIdents(object = run1.combined.v10, 
                               "0" = "Muscle 1",
                               "1" = "Stem C",
                               "2" = "Stem D",
                               "3" = "Stem F",
                               "4" = "Stem A",
                               "5" = "Stem B",
                               "6" = "Neuron 1",
                               "7" = "Muscle 2",
                               "8" = "Neuron 2",
                               "9" = "Parenchyma 1",
                               "10" = "Stem E",
                               "11" = "Parenchyma 2",
                               "12" = "Protonephridia",
                               "13" = "Tegument",
                               "14" = "Neuron 3",
                               "15" = "Neuron 5",
                               "16" = "Stem G",
                               "17" = "Neuron 4", 
                              "18" = "Neuron 6")


run1.combined.v10[["merge.ident"]] <- Idents(object = run1.combined.v10)
run1.combined.v10[["may.ident"]] <- Idents(object = run1.combined.v10)

DimPlot(run1.combined.v10, reduction = "umap", label=TRUE) #visulaises the UMAP
p2 <- DimPlot(run1.combined.v10, reduction = "umap", label = TRUE, repel = TRUE)
p2
```

```{r}
run1.no_W <- AddMetaData(object = run1.no_W, metadata = run1.combined.v10$may.ident, col.name = 'may.ident')
Idents(run1.no_W) <- run1.no_W$may.ident
```

```{r}
p2 <- DimPlot(run1.no_W, reduction = "umap", label = TRUE, repel = TRUE)
p2
ggsave("run1clust_55PC_1res_integrate.run1.no_W_maylabels.pdf")
ggsave("run1clust_55PC_1res_integrate.run1.no_W_maylabels_big.pdf", width = 35, height = 25, units = c('cm'))
```

Make a new color pallete for the 'fancy' umap
```{r}
new_pal <- c("#9E0059","#007aaa","#ffb703","#B3E9C7","#fb8500","#7851a9","#00325b","#8ACB88","#107E7D", "#FB6376", "#c40c18", "#FFFD82", "#2191FB", "#690500", "#57467B", "#B57F50","#2C514C","#c4b7cb" ,"#FFCDB2" )
scales::show_col(new_pal)
plot1 <- DimPlot(run1.no_W, reduction = "umap", label = FALSE, repel = TRUE, label.box = FALSE) + NoLegend() +scale_color_manual(values = new_pal)
LabelClusters(plot1, id = "ident", color = 'black', size =4, repel = T,  box.padding = 1.75)

ggsave("run1.v10.no_W_umap_fancyoldlabels_nov23.pdf", width = 20, height = 15, units = c('cm'))
ggsave("run1.v10.no_W_umap_fancyoldlabels_nov23_small.pdf")
```